#!/bin/bash
##

set -e

# When hand-drilling, we want the holes small.
SMALL_HOLES=1  # todo: make this a command line option

if [ $# -lt 2 -o $# -gt 3 ] ; then
   echo "usage: $0 <options> <rsolution-dpi> <gerber-filename> [<drillfile>]" > /dev/stderr
   echo "Output on stdout." > /dev/stderr
   exit 1
fi

DPI=$1
IN_GERBER=$2
DRILL_FILE=$3

COPPER_LAYER="-f#000000ff $IN_GERBER"

if [ ! -z "$DRILL_FILE" ] ; then
   if [ $SMALL_HOLES -eq 0 ] ; then
       DRILL_LAYER="-f#ffffffff $DRILL_FILE"
   else
       sed 's/^T[0-9]*C.*/;\0/' < $DRILL_FILE > /tmp/orig.$$.drl
       ( for i in `seq 1 9` ; do echo "T0$i 0.01" ; done ) > /tmp/fake.$$.drl
       DRILL_LAYER="-f#ffffffff /tmp/orig.$$.drl -t/tmp/fake.$$.drl"
   fi
fi


# gerbv can't export the DPI in the png output file (working on it, requires
# patches to Cairo and gerbv). Till then, export first as PostScript, then
# generate PNG from it with proper DPI settings.

# .. generate PostScript
gerbv -xps -o/tmp/gerbvtmp.$$.ps -b"#ffffff" $DRILL_LAYER $COPPER_LAYER

# .. convert to PNG, set DPI.
`dirname $0`/ps2bwpng $DPI /tmp/gerbvtmp.$$.ps

rm -f /tmp/*.$$.drl /tmp/gerbvtmp.$$.ps
